package com.example.util.simpleshoppinglist.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.*

/**
 * Model class for shopping item.
 * Kotlin data class provides equals/hashCode, toString and copy methods.
 */
@Entity(tableName = "items")
data class Item (
    @PrimaryKey @ColumnInfo(name = "id")
    val id: String = UUID.randomUUID().toString(), // TODO UUID or autogenerated?

    @ColumnInfo(name = "name")
    var name: String = "",

    @ColumnInfo(name = "color")
    var color: Int = 0,

    /**
     * True if the item is listed (in the main list), false otherwise.
     */
    @ColumnInfo(name = "listed")
    var isListed: Boolean = false,

    /**
     * True if the item is listed but not checked yet, false if listed and checked.
     */
    @ColumnInfo(name = "active")
    var isActive: Boolean = false
)